# Generated by Django 4.2.6 on 2023-10-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household_appliances', '0002_remove_product_categories_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='household_appliances.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household_appliances.product')),
            ],
        ),
    ]
